### ISSUE TITLE
Licenses - Player Oppression Voices 1.13 vs Licenses - Voices 1.12 - With Dialogue Patch.zip vs  Licenses Voice 1-13.zip

### ISSUE THREAD

**Issue by hydrOHxide** [ConsolidatedSky/NEFARAM#10]
Manual Download List says
Licenses - Voices 1.12 - With Dialogue Patch.zip

Meanwhile, Wabbajack is looking for 
Licenses - Voices 1.13.zip

whereas LoversLab has Licenses Voice 1-13.zip or Licenses - Voices 1.12 - With Dialogue Patch.zip
https://www.loverslab.com/files/file/31635-licenses-player-oppression-voices/

Renaming the former to what Wabbajack is looking for won't make it hash.

**Comment by BlackStarNirm** [comment]
I manually downloaded the Voices 1.13.zip and Wabbajack still doesn't recognize it and asks me to download it manually while installing.. And even after successful download throws me an error and stops installing.

I've attached the log, please help.

[Wabbajack.current.log](https://github.com/ConsolidatedSky/NEFARAM/files/15174140/Wabbajack.current.log)

**Comment by BlackStarNirm** [comment]
This is fixed: Licenses - Voices 1.13 - With Dialogue Patch.zip <--- This has to be downloaded not Licenses - Voices 1.13 as mentioned in the title. For anyone who faces this issue.
