### ISSUE TITLE
Mod download error due to updates #2

### ISSUE THREAD

**Issue by DerMittelpunkt** [ConsolidatedSky/NEFARAM#14]
Hi, the same problem from yesterday came up again. Two mods got an update

Devious Devices - Laura's Bondage Shop (7-aug-2024) V3.51 3.51
Deviously Enchanted Chests V3.213 SE/LE

These are the newest versions from the same mods.

**Comment by Miorx** [comment]
having same issue, just need the old version of these so I can finish the download lol

**Comment by Jprice66** [comment]
Same here. This is my first time downloading the collection and I am just waiting on this one mod lol
