### ISSUE TITLE
Required mod deleted from NexusMods / Heels Sound 1.5 SSE

### ISSUE THREAD

**Issue by Gracko3000** [ConsolidatedSky/NEFARAM#17]
https://www.nexusmods.com/skyrimspecialedition/mods/62502?tab=files&file_id=259236

00:06:41.842 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2142 total files, 2147 matching filesize
00:06:41.925 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Heels Sound 1.5 SSE-62502-1-5-1643037371.7z (NexusDownloader+State|SkyrimSpecialEdition|62502|259236)
00:06:41.925 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

Tried to download file manually but Wabbajack ignores my pasted files into download folder

**Comment by Seatmeister** [comment]
Please check the nefaram discord server for more Info. The mod got deleted and the list is currently under maintenance.
