### ISSUE TITLE
Wabbajack NEFARAM install fail

### ISSUE THREAD

**Issue by Mumnoch** [ConsolidatedSky/NEFARAM#7]
Failed to install, I even went to https://www.patreon.com/posts/baka-motion-data-69839285 to download Baka Motion Data Pack 1.21v and it still won't install it. Then SLHH at https://www.loverslab.com/files/file/6217-sexlab-horrible-harassment-expansion-lese/ even if I manually download it when Wabbajack starts the install from Disk it deletes the SLHH I manually stick in the folder.

Please update to fix this or tell me how I can go in and force Wabbajack to install the SLHH and Baka Motion Data Pack to continue with this promising modlist. Thank you for your time.
[Wabbajack.current.log](https://github.com/ConsolidatedSky/NEFARAM/files/10366942/Wabbajack.current.log)

**Comment by ConsolidatedSky** [comment]
An update is coming out today to fix that
