### ISSUE TITLE
Weapons draw and sheath positioning and animation

### ISSUE THREAD

**Issue by jdkbph** [ConsolidatedSky/NEFARAM#8]
Hey folks.

Looking for some help regarding the ability to position weapons on my character. Previously this had not been a problem, or more accurately, a very nice-to-have.

With the newer version of SSE/AE needed to run Nefaram I am no longer seeing the required sliders {eg, weapon location when sheathed, weapon size, etc) in RaceMenu.

I tried adding the sliders by installing XPMSE, but that didn't help.

Any thoughts or ideas on how to fix this would be most appreciated.

JD

**Comment by ConsolidatedSky** [comment]
we use IED
