### ISSUE TITLE
BakaFactory ABC LE SE.7z

### ISSUE THREAD

**Issue by Aeaeren** [ConsolidatedSky/NEFARAM#9]
Google drive link doesn't work. I went to Lovers Lab and found it and it sent me to another site where I did find it but this is a newer version so the hash doesn't line up and the installation fails.

**Comment by BlackStarNirm** [comment]
Fixed now : https://drive.google.com/file/d/17Ox4I4P0rJUIHCPltum-iq8JTBx-vA9j/view
